module.exports = [
  { id: 45, name: "Assembly (NASM 2.14.02)", ace_id: "assembly_x86" },
  { id: 46, name: "Bash (5.0.0)", ace_id: "" },
  { id: 47, name: "Basic (FBC 1.07.1)", ace_id: "" },
  { id: 75, name: "C (Clang 7.0.1)", ace_id: "c_cpp" },
  { id: 76, name: "C++ (Clang 7.0.1)", ace_id: "c_cpp" },
  { id: 48, name: "C (GCC 7.4.0)", ace_id: "c_cpp" },
  { id: 52, name: "C++ (GCC 7.4.0)", ace_id: "c_cpp" },
  { id: 49, name: "C (GCC 8.3.0)", ace_id: "c_cpp" },
  { id: 53, name: "C++ (GCC 8.3.0)", ace_id: "c_cpp" },
  { id: 50, name: "C (GCC 9.2.0)", ace_id: "c_cpp" },
  { id: 54, name: "C++ (GCC 9.2.0)", ace_id: "c_cpp" },
  { id: 86, name: "Clojure (1.10.1)", ace_id: "clojure" },
  { id: 51, name: "C# (Mono 6.6.0.161)", ace_id: "csharp" },
  { id: 77, name: "COBOL (GnuCOBOL 2.2)", ace_id: "cobol" },
  { id: 55, name: "Common Lisp (SBCL 2.0.0)", ace_id: "lisp" },
  { id: 56, name: "D (DMD 2.089.1)", ace_id: "d" },
  { id: 57, name: "Elixir (1.9.4)", ace_id: "elixir" },
  { id: 58, name: "Erlang (OTP 22.2)", ace_id: "erlang" },
  { id: 44, name: "Executable", ace_id: "" },
  { id: 87, name: "F# (.NET Core SDK 3.1.202)", ace_id: "" },
  { id: 59, name: "Fortran (GFortran 9.2.0)", ace_id: "fortran" },
  { id: 60, name: "Go (1.13.5)", ace_id: "golang" },
  { id: 88, name: "Groovy (3.0.3)", ace_id: "groovy" },
  { id: 61, name: "Haskell (GHC 8.8.1)", ace_id: "haskell" },
  { id: 62, name: "Java (OpenJDK 13.0.1)", ace_id: "java" },
  { id: 63, name: "JavaScript (Node.js 12.14.0)", ace_id: "javascript" },
  { id: 78, name: "Kotlin (1.3.70)", ace_id: "kotlin" },
  { id: 64, name: "Lua (5.3.5)", ace_id: "lua" },
  { id: 89, name: "Multi-file program", ace_id: "" },
  { id: 79, name: "Objective-C (Clang 7.0.1)", ace_id: "objectivec" },
  { id: 65, name: "OCaml (4.09.0)", ace_id: "ocaml" },
  { id: 66, name: "Octave (5.1.0)", ace_id: "" },
  { id: 67, name: "Pascal (FPC 3.0.4)", ace_id: "pascal" },
  { id: 85, name: "Perl (5.28.1)", ace_id: "perl" },
  { id: 68, name: "PHP (7.4.1)", ace_id: "php" },
  { id: 43, name: "Plain Text", ace_id: "plain_text" },
  { id: 69, name: "Prolog (GNU Prolog 1.4.5)", ace_id: "prolog" },
  { id: 70, name: "Python (2.7.17)", ace_id: "python" },
  { id: 71, name: "Python (3.8.1)", ace_id: "python" },
  { id: 80, name: "R (4.0.0)", ace_id: "r" },
  { id: 72, name: "Ruby (2.7.0)", ace_id: "ruby" },
  { id: 73, name: "Rust (1.40.0)", ace_id: "rust" },
  { id: 81, name: "Scala (2.13.2)", ace_id: "scala" },
  { id: 82, name: "SQL (SQLite 3.27.2)", ace_id: "sql" },
  { id: 83, name: "Swift (5.2.3)", ace_id: "swift" },
  { id: 74, name: "TypeScript (3.7.4)", ace_id: "typescript" },
  { id: 84, name: "Visual Basic.Net (vbnc 0.0.0.5943)", ace_id: "" }
]
